runtime: python27
api_version: 1
threadsafe: true

env_variables:
    MY_NAME: 'Yabin Cui'

handlers:
- url: /css
  static_dir: css
- url: /.*
  secure: always
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
